{
  try {
    run2();
  }
 catch (  RuntimeException e) {
    _log.error("Error starting",e);
  }
}
